server:
  port: 8080

monitor:
  app-secret: abc12345

# ğŸ‘‡ InfluxDB é…ç½®
influx:
  url: http://localhost:8086
  token: GCqeNNPRnEarrVZPlQVb116O43O_9if2q6FlIj-OR8SxLLkMmB3Pg2kCBtQZzeS3_2-EiWnKGbjt4LaQvIL7Cw== #InfluxDB Token
  org: my-org
  bucket: monitor_bucket

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ğŸ‘‡ æ”¹æˆä½ çš„æ•°æ®åº“åœ°å€
    url: jdbc:mysql://localhost:3306/monitor_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  data:
    redis:
      # Redisåœ¨ç½‘ç»œä¸Šé»˜è®¤ä½¿ç”¨æ˜æ–‡ä¼ è¾“,å¦‚æœå¯¹æ•°æ®æ•æ„Ÿçš„,å¼€å‘ç¯å¢ƒæ¨èä½¿ç”¨å°†æœ¬åœ°6379ç«¯å£SSHéš§é“è¿æ¥åˆ°è¿œç¨‹6379ç«¯å£,ç”Ÿæˆç¯å¢ƒåˆ™æ¨èå¼€å¯Redis TLS/SSL
      host: ${REDIS_HOST} #å¡«å†™ä½ çš„Redis Host(ä¸»æœºå)
      port: 6379
      password: ${REDIS_PASSWORD} #å¡«å†™ä½ çš„Redis Password(å¯†ç )
      database: 0
      timeout: 5000ms
      # ğŸ‘‡ è¿™é‡Œæ˜¯è¿æ¥æ± é…ç½® (Lettuce)
      lettuce:
        pool:
          # æœ€å¤§è¿æ¥æ•°ï¼Œé»˜è®¤8ï¼Œç”Ÿäº§ç¯å¢ƒå»ºè®®è°ƒå¤§ï¼Œå¦‚ 32 æˆ– 64
          max-active: 32
          # æœ€å¤§ç©ºé—²è¿æ¥ï¼Œä¿æŒä¸€äº›è¿æ¥éšæ—¶å¯ç”¨
          max-idle: 8
          # æœ€å°ç©ºé—²è¿æ¥
          min-idle: 0
          # ä»æ± ä¸­è·å–è¿æ¥çš„æœ€å¤§ç­‰å¾…æ—¶é—´ï¼Œé…ç½®ä¸ºè´Ÿå€¼è¡¨ç¤ºæ— é™ç­‰å¾…
          max-wait: 10000ms

# MyBatis-Plus é…ç½® (å¯é€‰ï¼Œç”¨äºæ‰“å° SQL æ—¥å¿—ï¼Œæ–¹ä¾¿è°ƒè¯•)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: MonitorSystemSecurityKeyMustBeVeryLongAndComplex2024!

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com  # ä½ çš„ Bucket æ‰€åœ¨åœ°åŸŸèŠ‚ç‚¹
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}         # RAM ç”¨æˆ·çš„ Key
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET} # RAM ç”¨æˆ·çš„ Secret
    bucket-name: server-monitor-xu               # Bucket åç§°
    # è®¿é—®åŸŸåå‰ç¼€ (Bucketå.èŠ‚ç‚¹)
    url-prefix: https://server-monitor-xu.oss-cn-shenzhen.aliyuncs.com/