server:
  port: 8080

monitor:
  app-secret: abc12345

# ğŸ‘‡ InfluxDB é…ç½®
influx:
  url: http://localhost:8086
  token: GCqeNNPRnEarrVZPlQVb116O43O_9if2q6FlIj-OR8SxLLkMmB3Pg2kCBtQZzeS3_2-EiWnKGbjt4LaQvIL7Cw== #InfluxDB Token
  org: my-org
  bucket: monitor_bucket

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ğŸ‘‡ æ”¹æˆä½ çš„æ•°æ®åº“åœ°å€
    url: jdbc:mysql://localhost:3306/monitor_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

# MyBatis-Plus é…ç½® (å¯é€‰ï¼Œç”¨äºæ‰“å° SQL æ—¥å¿—ï¼Œæ–¹ä¾¿è°ƒè¯•)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: MonitorSystemSecurityKeyMustBeVeryLongAndComplex2024!