server:
  port: 8081  # 客户端运行在 8081 端口，避免和未来服务端的 8080 冲突

monitor:
  # 使用宿主机的 WLAN IP
  server-base-url: http://10.13.13.161:8080 # 服务端根地址,需要时直接在代码中拼接字符串
  server-url: http://10.13.13.161:8080/api/monitor/report  # 服务端接收接口地址
  app-id: 1001           # 假设分配给这台机器的 ID
  app-secret: abc12345   # 通信密钥 (鉴权用)
  interval: 5000         # 采集间隔 (毫秒)，5秒一次